CREATE TABLE nivel_risco (
  id INTEGER PRIMARY KEY,
  nivel_risco VARCHAR(255) NOT NULL
);

CREATE TABLE previsao ( 
  id BIGSERIAL PRIMARY KEY,
  tipo_previsao VARCHAR(100) NOT NULL, 
  probabilidade DOUBLE PRECISION NOT NULL,
  nivel_risco VARCHAR(255),
  recomendacao VARCHAR(255) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE genero (
  id INTEGER PRIMARY KEY,
  genero VARCHAR(255) NOT NULL
);
CREATE TABLE pais (
  id INTEGER PRIMARY KEY,
  pais VARCHAR(255) NOT NULL
);